name: main Push
run-name: Push to Master by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/documentation/**'
      - 'iac/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v3
        id: release
        with:
          default-branch: main
          path: .
          package-name: nx-monorepo
          release-type: node
      - name: Print release outputs
        shell: bash
        run: | 
          echo "release_created: ${{ steps.release.outputs.release_created }}"


  build-environment-cache:
    if: ${{!needs.release-please.outputs.release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: Print build-environment-cache outputs
        shell: bash
        run: | 
          echo build-environment-cache

  deploy-production:
    if: ${{needs.release-please.outputs.release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: Print deploy-production outputs
        shell: bash
        run: | 
          echo deploy-production
